name: Build Linux DEB

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build-linux:
    name: Linux DEB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - uses: gradle/actions/setup-gradle@v4

      - name: Build with Fastlane
        shell: bash
        run: bundle exec fastlane desktop_deb

      - uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: dist/*
          if-no-files-found: error
